services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  shard1:
    build: ./shard
    environment:
      SHARD_ID: shard1
      SHARD_ADDR: shard1:8081
      PORT: "8081"
      ETCD_ENDPOINTS: "etcd:2379"
      OLLAMA_URL: "http://host.docker.internal:11434"
      DATA_DIR: "/data"
      INTERNAL_SECRET: "cluster-secret-key-12345"
    ports:
      - "8081:8081"
    volumes:
      - ./data/shard1:/data
    depends_on:
      - etcd

  shard2:
    build: ./shard
    environment:
      SHARD_ID: shard2
      SHARD_ADDR: shard2:8081
      PORT: "8081"
      ETCD_ENDPOINTS: "etcd:2379"
      OLLAMA_URL: "http://host.docker.internal:11434"
      DATA_DIR: "/data"
      INTERNAL_SECRET: "cluster-secret-key-12345"
    ports:
      - "8082:8081"
    volumes:
      - ./data/shard2:/data
    depends_on:
      - etcd

  shard3:
    build: ./shard
    environment:
      SHARD_ID: shard3
      SHARD_ADDR: shard3:8081
      PORT: "8081"
      ETCD_ENDPOINTS: "etcd:2379"
      OLLAMA_URL: "http://host.docker.internal:11434"
      DATA_DIR: "/data"
      INTERNAL_SECRET: "cluster-secret-key-12345"
    ports:
      - "8083:8081"
    volumes:
      - ./data/shard3:/data
    depends_on:
      - etcd

  coordinator:
    build:
      context: .
      dockerfile: ./coordinator/Dockerfile
    environment:
      PORT: "8080"
      REDIS_ADDR: "redis:6379"
      ETCD_ENDPOINTS: "etcd:2379"
      OLLAMA_URL: "http://host.docker.internal:11434"
      API_KEY: "supersecret-admin-key"
      INTERNAL_SECRET: "cluster-secret-key-12345"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - etcd

      - shard1
      - shard2
      - shard3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./ops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning
